.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH SYSEXXER-NG 1 "october  31, 2018"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
.br
sysexxer-ng \- a universal tool to exchange MIDI system-exclusive data.
.SH SYNOPSIS
.br
.B sysexxer-ng
.RI "file"
.br
.SH DESCRIPTION
.br
.B sysexxer-ng
is a universal tool to exchange MIDI system-exclusive data.
.br
.br
Features:
.br
- it works with both ALSA and/or JACK,
.br
- it supports localization (currently French and English),
.br
- it is built with FLTK.

.SH OPTIONS
.br
There is no option.

.SH AUTHOR
.br
This manual page was written by Olivier Humbert <trebmuh@tuxfamily.org>.
