.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH SYSEXXER-NG 1 "octobre  31, 2018"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NOM
.br
sysexxer-ng \- est un outil universel pour échanger des données system-exclusive
MIDI.
.SH SYNOPSIS
.br
.B sysexxer-ng
.RI "fichier"
.br
.SH DESCRIPTION
.br
.B sysexxer-ng
est un outil universel pour échanger des données system-exclusive MIDI.
.br
.br
Fonctionnalités :
.br
- il fonctionne avec ALSA et/ou JACK,
.br
- il permet la localisation (actuellement français et anglais),
.br
- il est construit avec FLTK.

.SH OPTIONS
.br
Il n'y a pas d'option.

.SH AUTEUR
.br
Cette page de manuel a été écrite par Olivier Humbert <trebmuh@tuxfamily.org>.
